kind: pipeline
type: kubernetes
name: default

trigger:
  event:
    exclude: [ promote ]

steps:
  - name: dependencies
    image: node
    commands:
      - npm install
  - name: build
    image: node
    commands:
      - npm run build
  - name: deploy
    image: plugins/gh-pages
    settings:
      username: ca8227d7a5ee7582499d8599cca7d40bf08fecd9
      password: x-oauth-basic
      upstream_name: https
      target_branch: master
      pages_directory: build/

