kind: pipeline
type: kubernetes
name: default

trigger:
  event:
    exclude: [ promote ]

steps:
  - name: dependencies
    image: node
    commands:
      - npm install
  - name: build
    image: node
    commands:
      - npm run build
  - name: deploy
    image: plugins/gh-pages
    settings:
      remote_url: git@github.com:paschini/paschini.github.io.git
      ssh_key:
        from_secret: DRONE_KEY
      target_branch: master
      pages_directory: build/

