kind: pipeline
type: kubernetes
name: default

trigger:
  event:
    exclude: [ promote ]

steps:
  - name: dependencies
    image: node
    commands:
      - npm install
  - name: deploy
    image: node
    commands:
      - npm run deploy